apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: elasticstacks.elasticstack.ibm.com
  labels:
    app.kubernetes.io/instance: "common-logging"
    app.kubernetes.io/managed-by: elasticstacks.elasticstack.ibm.com
    app.kubernetes.io/name: elasticstacks.elasticstack.ibm.com
spec:
  group: elasticstack.ibm.com
  names:
    kind: ElasticStack
    listKind: ElasticStackList
    plural: elasticstacks
    singular: elasticstack
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true
