channels:
- currentCSV: ibm-elastic-stack-operator.v3.0.5
  name: stable-v1
- currentCSV: ibm-elastic-stack-operator.v3.1.1
  name: dev
defaultChannel: stable-v1
packageName: ibm-elastic-stack-operator-app
