scorecard:
  # Setting a global scorecard option
  output: json
  plugins:
    # `basic` tests configured to test 2 CRs
    - basic:
        cr-manifest:
          - "deploy/crds/elasticstack.ibm.com_v1alpha1_elasticstack_cr.yaml"
    # `olm` tests configured to test 2 CRs
    - olm:
        cr-manifest:
          - "deploy/crdselasticstack.ibm.com_v1alpha1_elasticstack_cr.yaml"
        csv-path: "deploy/olm-catalog/ibm-elastic-stack-operator/0.0.1/ibm-elastic-stack-operator.v0.0.1.clusterserviceversion.yaml"
