apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: elasticstacks.elasticstack.ibm.com
spec:
  group: elasticstack.ibm.com
  names:
    kind: ElasticStack
    listKind: ElasticStackList
    plural: elasticstacks
    singular: elasticstack
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true #this would need to be fleshed out the way deploy/crds/elasticstack.ibm.com_elasticstacks_crd.yaml was for ResourceShcemaIsValid
  versions:
  - name: v1alpha1
    served: true
    storage: true
