# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2019. All Rights Reserved.
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "elasticsearch.fullname" . }}-config"
  labels:
    app: "{{ template "elasticsearch.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    component: "{{ .Values.elasticsearch.name }}"
data:
  data.yml: |-
{{ tpl (.Files.Get "elasticsearch/general.config") . | indent 4 }}
    node.master: true
    node.data: true
    path.data: /usr/share/elasticsearch/data/6.x
  roles.yml: |-
{{ .Files.Get "xpack/roles.yml" | indent 4 }}
  role_mapping.yml: |-
{{ .Files.Get "xpack/role_mapping.yml" | indent 4 }}
