{{ template "elk.settings.all.prepare" . -}}
{{- if .Values.general.pkiInitEnabled }}
#
# Copyright 2020 IBM Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http:#www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  labels:
    app: "{{ template "elasticsearch.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "pki-init"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: "{{ template "elasticsearch.fullname" . }}-pki-init"
  annotations:
<<<<<<< HEAD
=======
    "helm.sh/hook": "pre-install, pre-rollback, post-delete"
    "helm.sh/hook-weight": "-19"
    "helm.sh/hook-delete-policy": "hook-succeeded, before-hook-creation"
>>>>>>> - fixes 37572
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "list", "get", "delete", "patch"]
{{- end }}
