{{ template "elk.settings.all.prepare" . -}}
{{- if .Values.general.pkiInitEnabled }}
# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2019. All Rights Reserved.
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ template "elasticsearch.fullname" . }}-pki-delete"
  labels:
    app: "{{ template "elasticsearch.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "secret-delete"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-delete-policy": hook-succeeded
    "helm.sh/hook-weight": "-9"
spec:
  template:
    metadata:
      labels:
        app: "{{ template "elasticsearch.fullname" . }}"
        component: "secret-delete"
        role: "cleanup"
        release: "{{ .Release.Name }}"
        chart: "{{ .Chart.Name }}"
        heritage: "{{ .Release.Service }}"
    spec:
{{ include "image.pullSecret" . | indent 6 }}
      containers:
      - name: kubectl
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          runAsUser: 1000
          runAsNonRoot: true
        image: "{{ .Values.elasticsearch.pkiInitImage.repository }}:{{ .Values.elasticsearch.pkiInitImage.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
{{ toYaml .Values.elasticsearch.pkiInitImage.resources | indent 12 }}
        command: ['/bin/sh']
        args: ['-c', 'kubectl delete secret {{ template "fullname" . }}-certs --ignore-not-found=true && kubectl delete secret {{ template "fullname" . }}-ca --ignore-not-found=true']
      restartPolicy: Never
{{- end }}
