apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: "{{ template "elasticsearch.fullname" . }}"
    component: "{{ .Values.elasticsearch.data.name }}"
    role: "data"
    release: "{{ .Release.Name }}"
    chart: "{{ .Chart.Name }}"
    heritage: "{{ .Release.Service }}"
  name: "{{ template "elasticsearch.fullname" . }}"
