# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2019. All Rights Reserved.
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
{{ template "elk.settings.all.prepare" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: "{{ template "filebeat.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.filebeat.name }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: "{{ template "filebeat.fullname" . }}-config"
data:
  filebeat.yml: |-
{{ tpl (.Files.Get "filebeat/filebeat.yml") . | indent 4 }}
