apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: "{{ template "elasticsearch.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.filebeat.name }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    role: "filebeat"
  name: "{{ template "filebeat.fullname" . }}"
