apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: "{{ template "job.fullname" . }}"
    component: "job"
    role: "data"
    release: "{{ .Release.Name }}"
    chart: "{{ .Chart.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
  name: "{{ template "job.fullname" . }}"
