{{- if .Values.kibana.install -}}
# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2019. All Rights Reserved.
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "kibana.fullname" . }}-config"
  labels:
    app: "{{ template "elasticsearch.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.kibana.name }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
data:
  kibana.yml: |-
{{ tpl (.Files.Get "kibana/kibana.yml") . | indent 4 }}
{{- end }}
