{{- if .Values.kibana.install -}}

# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2019. All Rights Reserved.
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: "{{ template "elasticsearch.fullname" . }}"
    release: "{{ .Release.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
  name: {{ template "kibana.fullname" . }}-init-entrypoint
data:
  entrypoint.sh: |-
{{ tpl (.Files.Get "kibana-init/entrypoint.sh") . | indent 4 }}
{{ end }}
