# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2019. All Rights Reserved.
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "logstash.fullname" . }}-config"
  labels:
    app: "{{ template "elasticsearch.fullname" . }}"
    component: "{{ .Values.logstash.name }}"
    release: "{{ .Release.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
data:
  logstash.yml: |-
{{ tpl (.Files.Get "logstash/logstash.yml") . | indent 4 }}
  jvm.options: |-
{{ tpl (.Files.Get "logstash/jvm.options") . | indent 4 }}
  log4j2.properties: |-
{{ tpl (.Files.Get "logstash/log4j2.properties") . | indent 4 }}
  startup.options: |-
{{ tpl (.Files.Get "logstash/startup.options") . | indent 4 }}
  es-template.json: |-
{{ tpl (.Files.Get "logstash/es-template.json") . | indent 4 }}
