apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibm-elastic-stack-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ibm-elastic-stack-operator
  template:
    metadata:
      labels:
        name: ibm-elastic-stack-operator
      annotations:
         "openshift.io/scc": "restricted"
         productName: IBM Cloud Platform Common Services
         productID: "068a62892a1e4db39641342e592daa25"
         productVersion: "3.4.0"
         productMetric: FREE
    spec:
      serviceAccountName: ibm-elastic-stack-operator
      containers:
        - name: ibm-elastic-stack-operator
          # 3.1.2
          # image: quay.io/opencloudio/ibm-elastic-stack-operator@sha256:replace
          image: quay.io/opencloudio/ibm-elastic-stack-operator:3.1.2
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "elastic-stack-operator"
