apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibm-elastic-stack-operator
  labels:
    app.kubernetes.io/instance: logging
    app.kubernetes.io/managed-by: ibm-elastic-stack-operator
    app.kubernetes.io/name: ibm-elastic-stack-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ibm-elastic-stack-operator
  template:
    metadata:
      labels:
        name: ibm-elastic-stack-operator
        app.kubernetes.io/instance: logging
        app.kubernetes.io/managed-by: ibm-elastic-stack-operator
        app.kubernetes.io/name: ibm-elastic-stack-operator
      annotations:
         "openshift.io/scc": "restricted"
         productName: IBM Cloud Platform Common Services
         productID: "068a62892a1e4db39641342e592daa25"
         productVersion: "3.4.0"
         productMetric: FREE
    spec:
      serviceAccountName: ibm-elastic-stack-operator
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                  - amd64
                  - ppc64le
                  - s390x
      containers:
        - name: ibm-elastic-stack-operator
          # 3.1.2
          # image: quay.io/opencloudio/ibm-elastic-stack-operator@sha256:replace
          image: quay.io/opencloudio/ibm-elastic-stack-operator@sha256:b4112a25ab1bf34842f4c599044b3196d684cb992db976c0b15102446b1dbf2d
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "elastic-stack-operator"
