kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ibm-elastic-stack-operator
  labels:
    app.kubernetes.io/instance: common-logging
    app.kubernetes.io/managed-by: ibm-elastic-stack-operator
    app.kubernetes.io/name: ibm-elastic-stack-operator
subjects:
- kind: ServiceAccount
  name: ibm-elastic-stack-operator
  namespace: ibm-common-services
roleRef:
  kind: ClusterRole
  name: ibm-elastic-stack-operator
  apiGroup: rbac.authorization.k8s.io
