kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: elastic-stack-operator
subjects:
- kind: ServiceAccount
  name: elastic-stack-operator
  # TODO
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: elastic-stack-operator
  apiGroup: rbac.authorization.k8s.io
