filebeat.config:
  inputs:
    # Mounted `filebeat-inputs` configmap:
    path: ${path.config}/inputs.d/*.yml
    # Reload inputs configs as they change:
    reload.enabled: true
  modules:
    path: ${path.config}/modules.d/*.yml
    # Reload module configs as they change:
    reload.enabled: true
output.logstash:
  hosts: {{ .Values.logstash.name }}:{{ .Values.logstash.port }}
  timeout: 15
{{- if .Values.elasticsearch.security.authc.enabled }}
  ssl.certificate_authorities: ["/usr/share/elasticsearch/config/tls/ca.crt"]
  ssl.certificate: "/usr/share/elasticsearch/config/tls/filebeat.crt"
  ssl.key: "/usr/share/elasticsearch/config/tls/filebeat.key"
  ssl.key_passphrase: ${APP_KEYSTORE_PASSWORD}
{{- end }}
logging.level: info

# Monitoring settings
{{- if .Values.xpack.monitoring }}
xpack.monitoring:
  enabled: true
  {{- if .Values.elasticsearch.security.authc.enabled }}
  elasticsearch:
    hosts: ["https://{{ .Values.elasticsearch.name }}:{{ .Values.elasticsearch.client.restPort }}"]
    username:
    password:
    ssl:
      certificate_authorities: ["/usr/share/elasticsearch/config/tls/ca.crt"]
      certificate: "/usr/share/elasticsearch/config/tls/curator.crt"
      key: "/usr/share/elasticsearch/config/tls/curator.key"
      key_passphrase: ${APP_KEYSTORE_PASSWORD}
  {{- else }}
  elasticsearch.hosts: ["http://{{ .Values.elasticsearch.name }}:{{ .Values.elasticsearch.client.restPort }}"]
  {{- end }}
{{- end }}


