{
  "apiVersion": "elasticstack.ibm.com/v1alpha1",
  "kind": "ElasticStack",
  "metadata": {
    "name": "logging"
  },
  "spec": {
    "image": {
      "pullSecret": {
        "enabled": false,
        "name": "infra-registry-key"
      }
    },
    "curator": {
      "tolerations": [
        {
          "effect": "NoSchedule",
          "key": "dedicated",
          "operator": "Exists"
        }
      ]
    },
    "elasticsearch": {
      "client": {
        "tolerations": [
          {
            "effect": "NoSchedule",
            "key": "dedicated",
            "operator": "Exists"
          }
        ]
      },
      "data": {
        "replicas": 1,
        "storage": {
          "persistent": true,
          "useDynamicProvisioning": true
        },
        "tolerations": [
          {
            "effect": "NoSchedule",
            "key": "dedicated",
            "operator": "Exists"
          }
        ]
      },
      "master": {
        "tolerations": [
          {
            "effect": "NoSchedule",
            "key": "dedicated",
            "operator": "Exists"
          }
        ]
      },
      "security": {
        "authz": {
          "enabled": true,
          "provider": "icp"
        }
      }
    },
    "filebeat": {
      "scope": {
        "namespaces": [],
        "nodes": {}
      },
      "tolerations": [
        {
          "effect": "NoSchedule",
          "key": "dedicated",
          "operator": "Exists"
        }
      ]
    },
    "general": {
      "environment": "Openshift",
      "ingressPort": 443
    },
    "kibana": {
      "access": "ingress",
      "ingress": {
        "labels": {
          "inmenu": "false",
          "target": "platform-logging"
        },
        "path": "/kibana"
      },
      "replicas": 1,
      "security": {
        "authc": {
          "enabled": true,
          "provider": "icp"
        },
        "authz": {
          "enabled": false,
          "icp": {
            "authorizedNamespaces": []
          },
          "provider": "icp"
        }
      },
      "service": {
        "annotations": {
          "id": "add-ons",
          "name": "Logging",
          "roles": "ClusterAdministrator,Administrator,Operator,Viewer,Auditor,Editor"
        },
        "labels": {
          "inmenu": "false",
          "target": "platform-logging"
        },
        "path": "/kibana"
      },
      "tolerations": [
        {
          "effect": "NoSchedule",
          "key": "dedicated",
          "operator": "Exists"
        }
      ]
    },
    "logstash": {
      "port": 5044,
      "replicas": 1,
      "tolerations": [
        {
          "effect": "NoSchedule",
          "key": "dedicated",
          "operator": "Exists"
        }
      ]
    },
    "nameOverride": "elk",
    "security": {
      "ca": {
        "external": {
          "certFieldName": "tls.crt",
          "keyFieldName": "tls.key",
          "secretName": "cs-ca-certificate-secret"
        },
        "origin": "internal"
      },
      "tls": {
        "version": "TLSv1.2"
      }
    }
  }
}