kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: managed-logging
priority: 10
allowHostDirVolumePlugin: true
allowHostIPC: false
allowHostNetwork: false
allowHostPID: true
allowHostPorts: false
allowPrivilegeEscalation: true
allowPrivilegedContainer: true
allowedCapabilities:
- SYS_ADMIN
- SYS_RESOURCE
defaultAddCapabilities: []
fsGroup:
  type: RunAsAny
readOnlyRootFilesystem: false
requiredDropCapabilities: []
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
volumes:
- configMap
- secret
- emptyDir
seccompProfiles:
- docker/default
users:
- system:serviceaccount:ibm-common-services:default
